[phases.setup]
nixPkgs = ['python3', 'pip']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "No build step needed for Flask app"']

[start]
cmd = 'gunicorn -b 0.0.0.0:$PORT app:app'